[referral_email]
"Carlos De Los Santos" = "deloc00@voelker-controls.com"
"Chris Dillon" = "dillc00@voelker-controls.com"
"Scott Durbin" = "durbs00@voelker-controls.com"
"Brian Floyd" = "floyb00@voelker-controls.com"
"Sean Kelly" = "kells00@voelker-controls.com"
"Rob McCullough" = "mccur00@voelker-controls.com"
"Matt Rasnic" = "rasnm00@voelker-controls.com"
"David Voelker" = "voeld00@voelker-controls.com"
"Todd Voelker" = "voelt00@voelker-controls.com"
"Dave Waldbillig" = "waldd00@voelker-controls.com"
"Kody Robertson" = "robek00@voelker-controls.com"
"DAYTON" = "floyb00@voelker-controls.com"
"CINCINNATI" = "floyb00@voelker-controls.com"
"JC Gentile" = "gentj00@voelker-controls.com"
"Russell Hahn" = "hahnr00@voelker-controls.com"
"Chris Lasita" = "lasic00@voelker-controls.com"
"Adam Frost" = "frosa00@voelker-controls.com"
"Bryan Steller" = "stelb00@voelker-controls.com"
